export const FETCH_SITE_SETTINGS = "FETCH_SITE_SETTINGS";
export const FETCH_SITE_SETTINGS_SUCCESS = "FETCH_SITE_SETTINGS_SUCCESS";
export const FETCH_SITE_SETTINGS_FAILED = "FETCH_SITE_SETTINGS_FAILED";

// HOME
export const FETCH_HOME_CONTENT = "FETCH_HOME_CONTENT";
export const FETCH_HOME_CONTENT_SUCCESS = "FETCH_HOME_CONTENT_SUCCESS";
export const FETCH_HOME_CONTENT_FAILED = "FETCH_HOME_CONTENT_FAILED";

//CONTACT US
// Contact Us and NEwsletter Availability Form
export const SAVE_CONTACT_QUERY = "SAVE_CONTACT_QUERY";
export const SAVE_CONTACT_QUERY_SUCCESS = "SAVE_CONTACT_QUERY_SUCCESS";
export const SAVE_CONTACT_QUERY_FAILED = "SAVE_CONTACT_QUERY_FAILED";

export const SAVE_NEWSLETTER = "SAVE_NEWSLETTER";
export const SAVE_NEWSLETTER_SUCCESS = "SAVE_NEWSLETTER_SUCCESS";
export const SAVE_NEWSLETTER_FAILED = "SAVE_NEWSLETTER_FAILED";

export const SAVE_AVAILABILITY_REQUEST = "SAVE_AVAILABILITY_REQUEST";
export const SAVE_AVAILABILITY_REQUEST_SUCCESS = "SAVE_AVAILABILITY_REQUEST_SUCCESS";
export const SAVE_AVAILABILITY_REQUEST_FAILED = "SAVE_AVAILABILITY_REQUEST_FAILED";

// AUTH
export const CREATE_ACCOUNT_MESSAGE = "CREATE_ACCOUNT_MESSAGE";
export const CREATE_ACCOUNT_MESSAGE_SUCCESS = "CREATE_ACCOUNT_MESSAGE_SUCCESS";
export const CREATE_ACCOUNT_MESSAGE_FAILED = "CREATE_ACCOUNT_MESSAGE_FAILED";

export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";

export const SIGN_IN_MESSAGE = "SIGN_IN_MESSAGE";
export const SIGN_IN_MESSAGE_SUCCESS = "SIGN_IN_MESSAGE_SUCCESS";
export const SIGN_IN_MESSAGE_FAILED = "SIGN_IN_MESSAGE_FAILED";

export const RESET_PASSWORD_LINK = "RESET_PASSWORD_LINK";
export const RESET_PASSWORD_LINK_SUCCESS = "RESET_PASSWORD_LINK_SUCCESS";
export const RESET_PASSWORD_LINK_FAILED = "RESET_PASSWORD_LINK_FAILED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

// USER Dashboard
export const FETCH_USER_DASHBOARD_DATA = "FETCH_USER_DASHBOARD_DATA";
export const FETCH_USER_DASHBOARD_DATA_SUCCESS = "FETCH_USER_DASHBOARD_DATA_SUCCESS";
export const FETCH_USER_DASHBOARD_DATA_FAILED = "FETCH_USER_DASHBOARD_DATA_FAILED";

export const SAVE_USER_ACCOUNT_SETTINGS = "SAVE_USER_ACCOUNT_SETTINGS";
export const SAVE_USER_ACCOUNT_SETTINGS_SUCCESS = "SAVE_USER_ACCOUNT_SETTINGS_SUCCESS";
export const SAVE_USER_ACCOUNT_SETTINGS_FAILED = "SAVE_USER_ACCOUNT_SETTINGS_FAILED";

export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAILED = "CHANGE_USER_PASSWORD_FAILED";

export const FETCH_SELLER_WISHLIST_DATA = "FETCH_SELLER_WISHLIST_DATA";
export const FETCH_SELLER_WISHLIST_DATA_SUCCESS = "FETCH_SELLER_WISHLIST_DATA_SUCCESS";
export const FETCH_SELLER_WISHLIST_DATA_FAILED = "FETCH_SELLER_WISHLIST_DATA_FAILED";

export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS";
export const REMOVE_WISHLIST_FAILED = "REMOVE_WISHLIST_FAILED";

// Seller Dashboard
export const FETCH_SELLER_DASHBOARD_DATA = "FETCH_SELLER_DASHBOARD_DATA";
export const FETCH_SELLER_DASHBOARD_DATA_SUCCESS = "FETCH_SELLER_DASHBOARD_DATA_SUCCESS";
export const FETCH_SELLER_DASHBOARD_DATA_FAILED = "FETCH_SELLER_DASHBOARD_DATA_FAILED";

export const FETCH_SELLER_ACCOUNT_SETTINGS = "FETCH_SELLER_ACCOUNT_SETTINGS";
export const FETCH_SELLER_ACCOUNT_SETTINGS_SUCCESS = "FETCH_SELLER_ACCOUNT_SETTINGS_SUCCESS";
export const FETCH_SELLER_ACCOUNT_SETTINGS_FAILED = "FETCH_SELLER_ACCOUNT_SETTINGS_FAILED";

export const SAVE_SELLER_ACCOUNT_SETTINGS = "SAVE_SELLER_ACCOUNT_SETTINGS";
export const SAVE_SELLER_ACCOUNT_SETTINGS_SUCCESS = "SAVE_SELLER_ACCOUNT_SETTINGS_SUCCESS";
export const SAVE_SELLER_ACCOUNT_SETTINGS_FAILED = "SAVE_SELLER_ACCOUNT_SETTINGS_FAILED";

export const CHANGE_SELLER_PASSWORD = "CHANGE_SELLER_PASSWORD";
export const CHANGE_SELLER_PASSWORD_SUCCESS = "CHANGE_SELLER_PASSWORD_SUCCESS";
export const CHANGE_SELLER_PASSWORD_FAILED = "CHANGE_SELLER_PASSWORD_FAILED";

export const FETCH_SELLER_ITEMS = "FETCH_SELLER_ITEMS";
export const FETCH_SELLER_ITEMS_SUCCESS = "FETCH_SELLER_ITEMS_SUCCESS";
export const FETCH_SELLER_ITEMS_FAILED = "FETCH_SELLER_ITEMS_FAILED";

export const FETCH_SELLER_NOTIFICATIONS = "FETCH_SELLER_NOTIFICATIONS";
export const FETCH_SELLER_NOTIFICATIONS_SUCCESS = "FETCH_SELLER_NOTIFICATIONS_SUCCESS";
export const FETCH_SELLER_NOTIFICATIONS_FAILED = "FETCH_SELLER_NOTIFICATIONS_FAILED";

export const ADD_NEW_ITEM = "ADD_NEW_ITEM";
export const ADD_NEW_ITEM_SUCCESS = "ADD_NEW_ITEM_SUCCESS";
export const ADD_NEW_ITEM_FAILED = "ADD_NEW_ITEM_FAILED";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED";

export const FETCH_SELLER_SUBSCRIPTIONS = "FETCH_SELLER_SUBSCRIPTIONS";
export const FETCH_SELLER_SUBSCRIPTIONS_SUCCESS = "FETCH_SELLER_SUBSCRIPTIONS_SUCCESS";
export const FETCH_SELLER_SUBSCRIPTIONS_FAILED = "FETCH_SELLER_SUBSCRIPTIONS_FAILED";

export const CSV_EXPORT = "CSV_EXPORT";
export const CSV_EXPORT_SUCCESS = "CSV_EXPORT_SUCCESS";
export const CSV_EXPORT_FAILED = "CSV_EXPORT_FAILED";


// CHECKOUT 
export const SAVE_SUBSCRIPTION = "SAVE_SUBSCRIPTION";
export const SAVE_SUBSCRIPTION_SUCCESS = "SAVE_SUBSCRIPTION_SUCCESS";
export const SAVE_SUBSCRIPTION_FAILED = "SAVE_SUBSCRIPTION_FAILED";
export const SAVE_SUBSCRIPTION_SUCCESS_SIGNUP = "SAVE_SUBSCRIPTION_SUCCESS_SIGNUP";

export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const UPDATE_SUBSCRIPTION_FAILED = "UPDATE_SUBSCRIPTION_FAILED";
